# Generated by Django 3.0 on 2019-12-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address_street_name', models.CharField(max_length=50)),
                ('address_suburb', models.CharField(max_length=50)),
                ('address_post_code', models.CharField(max_length=5)),
                ('address_state', models.CharField(max_length=2)),
                ('contact_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
