# Generated by Django 3.0 on 2019-12-16 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20191216_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default=datetime.datetime(2019, 12, 16, 9, 23, 58, 42601, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default=datetime.datetime(2019, 12, 16, 9, 24, 39, 53608, tzinfo=utc), max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
